[package]
name = "feathertalk-image"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
jpeg-decoder.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true
ndarray.workspace = true
ndarray-npy.workspace = true
serde_json.workspace = true
sha2.workspace = true
